### ISSUE TITLE
Other characters blindfolded her eye with something.

### ISSUE THREAD

**Issue by e8l** [LapisTech/Mekakure#3]
とりあえず、思いついたものと調査して出てきたものを挙げました。
不適切なものや誤りがありましたら、お手数ではございますが、適宜取捨選択や修正をしていただけましたら幸いです。

- ムガロ　[神撃のバハムート VIRGIN SOUL](https://shingekinobahamut-virginsoul.jp/character/mugaro/)　女性　左（髪）
- オイゲン　[グランブルーファンタジー](http://anime.granbluefantasy.jp/character/07.html)　男性　左（眼帯）
- ファフニール　[小林さんちのメイドラゴン](http://maidragon.jp/character/)　男性　右（髪）
- リゼの父　[ご注文はうさぎですか？？](http://www.gochiusa.com/index.html)　男性　左（眼帯）
- ネイキッド・スネーク（ビッグボス）　[METAL GEAR SOLIDシリーズ](http://www.konami.jp/kojima_pro/hd/mgs/)　男性　右（眼帯）
- エレーナ・アルシャヴィナ　[聖剣使いの禁呪詠唱](http://warubure-anime.com/)　女性　右（髪）
- 綾辻絢瀬　[落第騎士の英雄譚](http://www.ittoshura.com/character/index.html)　女性　右（髪）
- 貴徳原 カナタ　[落第騎士の英雄譚](http://www.ittoshura.com/character/index.html)　女性　両目（帽子）
- デキム　[デス・パレード](http://www.vap.co.jp/deathparade/)　男性　右（髪）
- 佐藤 潤　[WORKING!](http://www.wagnaria.com/character/)　男性　左（髪）
- 小鳥遊 泉　[WORKING!](http://www.wagnaria.com/character/)　女性　左（髪）
- 小鳥遊 静　[WORKING!](http://www.wagnaria.com/character/)　女性　左（髪）
- エリザベス・リオネス　[七つの大罪](http://www.7-taizai.net/)　女性　右（髪）
- ナルサス　[アルスラーン戦記](http://arslan.jp/2/characters/index.html)　男性　右（髪）
- 風間レヴィ　[トリニティセブン](http://trinity-7.com/profile/character03.php)　女性　左（髪）
- コウテイペンギン　[けものフレンズ](http://kemono-friends.jp/character/)　女性　左（髪）
- 伊武崎峻　[食戟のソーマ](http://shokugekinosoma.com/character/shun.html)　男性　両目（髪）
- 雪華綺晶　[ローゼンメイデン](http://www.tbs.co.jp/anime/rozen/chara/)　女性　右（バラ）
- 江角京子　[レーカン！](http://www.tbs.co.jp/anime/re-kan/chara/)　女性　左（髪）
- K・K　[血界戦線](http://kekkaisensen.com/1st/character/charaview.html)　女性　右（眼帯）
- 堕落王フェムト　[血界戦線](http://kekkaisensen.com/1st/character/charaview.html)　男性　両目（仮面？）
- 偏執王アリギュラ　[血界戦線](http://kekkaisensen.com/1st/character/charaview.html)　女性　両目（仮面？）
- クリス　[クロスアンジュ　天使と竜の輪舞](http://crossange.com/character/chris/)　女性　左（髪）
- レシオ　[ハマトラ](http://www.tv-tokyo.co.jp/anime/hamatora/sp/chara/index.html)　男性　右（眼帯）
- 針目縫　[キルラキル](http://www.kill-la-kill.jp/character/13.html)　女性　左（眼帯）
- 夏目残夏　[妖狐×僕 SS](http://www.inuboku.tv/character/chara_zange.html)　男性　右（髪・布）
- ヴィラル　[天元突破グレンラガン](http://www.gurren-lagann.net/tv/chara/index.html)　男性　右（髪）
- アディーネ　[天元突破グレンラガン](http://www.gurren-lagann.net/tv/chara/index.html)　女性　左（眼帯）
- はたけカカシ　[NARUTO](http://www.tv-tokyo.co.jp/anime/naruto/chara/)　男性　左（布？）
- 山中いの　[NARUTO](http://www.tv-tokyo.co.jp/anime/naruto/chara/)　女性　右（髪）
- 障子目蔵　[僕のヒーローアカデミア](http://heroaca.com/character.html)　男性　右（髪）
- 柳レイ子　[僕のヒーローアカデミア](http://heroaca.com/character.html)　女性　左（髪）
- 小森希乃子　[僕のヒーローアカデミア](http://heroaca.com/character.html)　女性　両目（髪）
- ももがー　[ガールズアンドパンツァー](http://girls-und-panzer.jp/chara_momoga.html)　女性　右（眼帯）
- 目野輪 冥　[ウィッチクラフトワークス](http://www.witch-cw-anime.jp/menowa_mei.html)　女性　右（眼帯）
- メドゥーサ　[ウィッチクラフトワークス](http://www.witch-cw-anime.jp/menowa_mei.html)　女性　両目（布？）
- 火々里 かざね　[ウィッチクラフトワークス](http://www.witch-cw-anime.jp/menowa_mei.html)　女性　右（髪）
- 鬼灯 火苗　[ウィッチクラフトワークス](http://www.witch-cw-anime.jp/menowa_mei.html)　女性　右（髪）

**Comment by HirokiMiyaoka** [comment]
メモ：ファフニールさんまで追加

**Comment by HirokiMiyaoka** [comment]
メモ：小鳥遊 静さんまで追加。

**Comment by e8l** [comment]
追加分です。

- 織田信長　[ドリフターズ](http://www.nbcuni.co.jp/rondorobe/anime/drifters/character/nobunaga.html)　男性　右（眼帯）
- ハンニバル　[ドリフターズ](http://www.nbcuni.co.jp/rondorobe/anime/drifters/character/hannibal.html)　男性　左（布）
- 伊達政宗　[戦国鳥獣戯画](http://www.kbc.co.jp/scg/)　男性　右（眼帯）
- ウォリック・アルカンジェロ　[GANGSTA](http://gangsta-project.com/character.php)　男性　左（眼帯）
- シグ　[GANGSTA](http://gangsta-project.com/character.php)　女性　右（眼帯）
- バルメ　[ヨルムンガンド](http://www.jormungand.tv/character.html)　女性　右（眼帯）
- ショコラーデ　[ヨルムンガンド](http://www.jormungand.tv/character.html)　女性　右（髪）
- ヨランダ　[ブラックラグーン](http://www.blacklagoon.jp/index_fla.html)　女性　右（眼帯）
- キング・ブラッドレイ　[鋼の錬金術師 FULLMETAL ALCHEMIST](http://www.hagaren.jp/fa/characters/index01.html)　男性　左（眼帯）
- オリヴィエ・ミラ・アームストロング　[鋼の錬金術師 FULLMETAL ALCHEMIST](http://www.hagaren.jp/fa/characters/index01.html)　女性　右（髪）
- ハッサン　[マギ](http://www.project-magi.com/news/contents.html?p=3&cat=CHARACTER)　男性　左（布）
- S・ナンド　[マギ](http://www.project-magi.com/news/contents.html?p=3&cat=CHARACTER)　男性　左（眼帯）
- 峰津院大和　[DEVIL SURVIVOR2 the animation](http://www.mbs.jp/ds2a/)　男性　右（髪）
- 室戸菫　[ブラック・ブレッド](http://www.black-bullet.net/contents/chara/sumire.html)　女性　右（髪）
- ティア・グランツ　[テイルズ オブ ジ アビス](http://www.tv-toa.jp/character/index.html)　女性　右（髪）
- ヨーク　[テイルズ オブ ジ アビス](http://www.tv-toa.jp/character/index.html)　男性　右（眼帯）
- ハヤト　[ポケットモンスター　ハートゴールド・ソウルシルバー](https://www.nintendo.co.jp/ds/ipkj/)　男性　右（髪）
- シロナ　[ポケットモンスター　サン・ムーン](http://www.pokemon.co.jp/ex/sun_moon/)　女性　左（髪）
- レイくん　[ぷよぷよシリーズ](http://puyo.sega.jp/PuyopuyoChronicle/character/index.html)　男性　両目（髪）
- レムレス　[ぷよぷよシリーズ](http://puyo.sega.jp/PuyopuyoChronicle/character/index.html)　男性　右（髪）
- ロゼッタ　スーパーマリオシリーズ　女性　右（髪）
- 纏一身　[キルラキル](http://www.kill-la-kill.jp/character/15.html)　男性　右（眼帯）
- サイラス・ノーマン　[学戦都市アスタリスク](http://asterisk-war.com/character/)　男性　両目（髪）
- 黒服　[極黒のブリュンヒルデ](http://www.vap.co.jp/gokukoku/character/index.html)　男性　右（髪）
- アードライ　[革命機ヴァルヴレイヴ](http://www.valvrave.com/character/#c15)　男性　左（髪）
- カイン　[革命機ヴァルヴレイヴ](http://www.valvrave.com/character/#c19)　男性　右（布）
- ジン　[キャプテン・アース](http://captain-earth.net/character/kill-t-gang.php)　男性　左（髪）
- ナジェンダ　[アカメが斬る！](http://akame.tv/character.html)　女性　右（眼帯）
- ラバック　[アカメが斬る！](http://akame.tv/character.html)　男性　左（髪）
- 鳳 美煌　[さばげぶっ！](http://sabagebu.com/character.html)　女性　左（髪）
- 漆原 半蔵　[はたらく魔王さま！](http://maousama.jp/chara.html)　男性　右（髪）
- ヤヌア・アイン　[戦勇。](http://senyu.tv/character/janua.html)　男性　右（髪）
- 囷巴　[ノラガミ](http://noragami-anime.net/chara/)　男性　右（眼帯）
- 蠃蚌　[ノラガミ](http://noragami-anime.net/chara/)　男性　左（布）

**Comment by HirokiMiyaoka** [comment]
すべて追加しました。ありがとうございます！
